name: video_thumbnail_pro
description: "A flutter plugin for creating a thumbnail from a local video file or from a video URL."
version: 0.7.3
homepage: https://github.com/arsarsars1/video_thumbnail_pro.git
repository: https://github.com/arsarsars1/video_thumbnail_pro

environment:
  sdk: ^3.5.6
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.1.8
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

flutter:
  plugin:
    implements: video_thumbnail_pro
    platforms:
      android:
        package: com.ars.video_thumbnail_pro
        pluginClass: VideoThumbnailProPlugin
      ios:
        pluginClass: VideoThumbnailProPlugin
      web:
        pluginClass: VideoThumbnailProWeb
        fileName: video_thumbnail_web.dart
